# Travis - Octopress Build scheme: http://darvin.github.com/blog/2013/01/13/Prose_Octopress_TravisIO/
branches:
  only:
    - source
language: ruby
rvm:
  - 1.9.3
before_script: 
  # Set read-write git origin
  - git remote set-url origin $REPO.git
  # Unpack ssh key for git
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  # Disable SSH server fingerprint verification
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # Set deployment target to github pages
  - rake setup_github_pages[$REPO]
  - git checkout -- _config.yml
script:
  # Generate site
  - rake generate
after_script:
  # Deploy!
  - rake deploy

env:
  global:
    # Repo read-write address
    - REPO="git@github.com:Sibylus/sibylus.github.com"
    - secure: "CGepqpoDbK8irvlmk3uux5XxE6/OAUdwIVXGt5rpuRZyexeSrvmso51DPEFc\n4AS/DvTT3gjfOePR43/ou/0AOx4OaQxPmh2F1M0zXSbvox4WLf+P/IJA56Yb\nTExVHHWkd8BOLwQxW9jrNEjGjf+cdKJzoLDdy2N6Kx+2uQcOro8="
    - secure: "4X3x2stLUfJiqm3SjYMhgCIH1aYPbe5F5yePY0JE6A/VGBaRhRHLwadDTBZ2\n/D7Jjj4JA/FmonPddbEPuHRQM+pBR3OdVQKMNLZ/JhomgiNT1DHBdADZt6CJ\nzYWNVachWKQrc9ftwP0kbDTqReWaSQyivTOjLasf9TNF1WtHUgM="
    - secure: "uWJEp90nqSyrTPTqb7tPFhbumL+Yk5WgT5avMcY6d1TsKtfiqsiwM5XI7510\n1pAf5POKrCnl5qrMNlCDKeuXO6BrpwQt3iOhwJpBVYppgDIjSIDvPBxUt2H8\n4j720KFB+gjZ5tTReEigaNnRV2A10sHaHMBdNpoPTY7FPIxBNAs="
    - secure: "1dQDW/7gtdwcpVtkxKzi9Rj/oTrUTijgZueWVNCtRnNeH2LDM787+70IadZQ\n6xH+wf2FmGdVEPZJmBiy+71LyH3V6KySIkcNvpPHAsoec20jlywPCzsMKOLM\nUj8aAzoScx7ygcL9ZnUAfoUj/93xBAdrXc5FRR89HVXgb1NFKkc="
    - secure: "8RCdPwUzLvXpv66eXDGU6Aa1GXstkXoZUDm8LMzxc2vGM1khbBL2XDjbRIUi\nhV8YK/1Rv7lOM1KjmIduZcTZfrWEIF1JUr8UK8eBdRr7WLWopAPXqLCS/Wez\nl7yTeamJlFf1711+egbNd3f7fnMS9xYOB6CiL0moArXd+XDX5jM="
    - secure: "OJV1z3NfZWM9lzKnMb/9scH7aV4bunhZlSI+1LffusFiJv4e4vwW5cmPhRZP\ng71D6cdlMw2jwkJeE+jkLKKHdFHKLuGPoQgSNqQuIVtndlJoaneHroYCokf6\n5c4gJSJkf1S1GT9COZSlims4V5RovbM4KREj0kzPu+XaGFInYg4="
    - secure: "W/AaY2cDrroG2cMYiqVg+EJ92Xoo3ZyN+9ZzqqU02OBVQ+RtyU5jrdkggoPo\nJfiSAm3WhorYpVdrAabjpmJHaOddR9etLWI21hlCbBHWDbMGmPZRq+llcyig\nR1IJXYmyfj3P0ZobxtyXqOs5uQz5adviKyvDTcnhe6W0VOD3rTk="
    - secure: "3HDN9fvOG5wT+oCzdGWeWp47A5zrRK4NVZdxiffP0yVBQo5Js+R1zIWlkP/x\njSTGhdJuDtOFlRkXJ4U1Ce8bT3zdMc/MajRS2B2cu4JlNYtwg76TZcOyr2dz\nVQ9oNOIPSwHRt3Z7m4KcjQBzbj6kAVSxYxJooz29p+7VYvxS5rw="
    - secure: "4T6wH908ZMCpVKJf5WbxK03TjJ8RKoF3vF0oSVrkHJIrwub/gs6dA2/Y4uef\nTaQf3eorF/ZZjP/MaE5WZPnHFKQ3MHBIpe0KjOdLV5pV2MWNXzFedEMe/d0k\nhL3WozpYSDcKYQm46SaWP9RZ9LqKzEmBzr4g3NGxNSa3knebRR4="
    - secure: "Z6pOe2OyOFfHX+D8qanLFRe07KntUwpaH8+6rR1+fkKspcGTabKMmwAR2ka1\nqkAlNa1g9rP03KGgmJcddeHkVPR6Ayg0rqnbWxLPW/F29sA0EczRoiY1HNAR\nKXBlvNw/VaT2rHnQ3OXDP16vFzKXxHrEseGUlBDcFmRJLCPrx9Q="
    - secure: "ZQa85chUhj6lA9okzxZCN2F7dhVXNDGu0Rug7TTX1G6TPYcJWfHal56dR48G\n9sggVn02yPEC+hPivIDWk4dpXiejMZWA8hjkTM3TrGiZ3X9wVj5UovbP+mzH\nu8QEbAjM5tRgpJkVcR7ikySmpOBMlNQ6yrV2TLivSE5XRfTgNFQ="
    - secure: "qUNbfqj3DxirIO3lHtIY4q9H5M+W0k4tLclII0UdZOGk2IZJg6kYkKuckton\n0hJ5w/CCCG+EtTAkYxaKnERlcey/Bd35BPAZ7fpkjqpZNabPSd3PCDfpk7Sz\nIUTbGIRcCHF1Hh7ezFNgS9M/DEZvucxdaYsdP7ZJAKMiYzc3YcA="
    - secure: "m9G00cUk4ELp9uSfjP+iMlgJkz5lghwyD9g3wxs/EuMrXBpmgWWupeJJV/Sg\nyg5KrwSoYUFZtRyQN9csVFSI5QYYFXu1xs/03e7I61UdPlcMXCcQg0PXX7Wv\ngFGJbbuuu/+1Rnp8C7R3XD16Am7mXF5/fAACK4VmjaSVHDE4lSs="
    - secure: "t6MF4EtoD9ciMTxYHquUzfivG+6xEZKep55fPxW1qsK4G9gac8K0Bk7DDfOG\nL0CJ+fdK5KO6v8rJlqvPMbw/TLnI62qchmqvH2Hyf3rC7Ig7oJLQQGQFO9JJ\nf5tGVpgwQuM1UWYwOT1pJoUuvvZzx1WOfRtApDbJtjcOppsUnss="
    - secure: "Gy2GwoOawaVXcntfq3r3tQQsQwmQyep8AodxndPxbZcEKm+mS/uZak5r/TdW\nJlSeY91WYFYusNmOCl2EVlJhcMP1hlxXgXTvrlb8V9BiofDf1Bk6ioI8ShX6\nEm9ByDLgwdJzn1/AsG1dnmm1OsCZB8YP6/MAAPGMToBlSDTwd0k="
    - secure: "cvH1+7qS4/GxhNtFa4osLfWXViJKLrF/5a8qiycLTDaSsWn9i03dZZOm9bPv\n+uzWrjPvplph0mZ+/WNgFXVJ7ZOi0CnzBEME/yw/2MQ5t6XfYaX3CsQ0Dc1V\nWqrNRbPXGf0MRrlJbHN6ePAo7L6MtDEpcZ8ogwXQ/xoU7Rv3NyQ="
    - secure: "Pg9ctNCyqHjkYwDW2mUrZE/GAkdvokH5hjadH71h9/3C7UfWTqbDw5Vypv7r\nX88oR9e8P1wiTXIR6eUjk2KcGajbU04ZeA1wUsdb/V5AjJWM6bz0TFrocxG8\n/peFLo5WkAgxrJ1TFR10btWx99FVnJvLGU/mI3v4c6c1BWOfiDo="
    - secure: "z7MnJ9GGVrAh1O2JnvzFYf90g74oji0C7Cneo7NtYbEruPymok+9JJW3ayCN\ngrVPWTLWUpZ4ruaxj8v4uOpglWsFi4aLFQiGFaHZnWa151krbVXqyKm5g5rP\nL1RDBIKVrOUgVmgposxgRJeNdr0eUEPVm5pb5SMpD1Pphdzf+Hk="
    - secure: "sWzE70lpRMPqosSEjSI/jI4C5Faq+ZofHzn3TKxjnqHvxolUlmZtLt7SaJfS\nxG+TIrDDdV/FguNPHjgxX0t0/mx7zBF6DWwcslcVbeCbusvkx1spTIrP44cF\n0bVN7FwQng69OQHesM/TnUQzo+Dxw6SFK7ulfgC1yOxnPJjdaGw="
    - secure: "7+PZPKK/WOF4bSwUHOyEp9ryy0kE/TRgMTHS7+1RedizuFPQFG6UfRllPNZl\nEixc2RnBteqeZawgTfjweCjS3Dy3XUTFStLsMQPrbLeFfGBGwxZHO/zdR7jk\nZP86HHo9kX808c1q0LROWvkCzUfp3obq3vKT+iU30bULK4Es5c0="
    - secure: "fo5RBM3tIlDNK/sAl8d3C9TI6zRYPW2+6MTD9kqJ/yX4muXM2uLhcRy+LaPr\nra40J6uNTwasADA/rw9b7ME68P8vCTki+2vzqXT+CMMpOQX3yJEZq3cU49MZ\naBFGJuyp2AITRRcJeYnuI0SIQWlvU0yzeHXZ/xYhhWTVP03JUTc="
    - secure: "P6ltK4QOVmSTqqEJrbuvxITqkKUJFkuD1VE40eFjOQ3YxjnC84e467PNQ066\nutySSVHt670WBQj3/AAqDfwm9Q9LA/guZYxE4Zs50n+tLRTPSgTfCaX6yVaX\nydPwiuitYgrfDYYjFKMTl7MGOQpwCxmNvcpamWXYtABJtRXHEDI="
    - secure: "doo1ZXSNPfQuCyplrWCqVDRtYIYRUEfCODeMo5ujEEnqeEQ7uw+H8SgaMVii\n995lNYytIuBFIQAXBhp30nlt/VU2iYA8Zasu8fsGYIQFKHvAdzhWhIEInGzC\nONTThVk60yTbxrbc9MDz2vHor/U5AWsjiTPvT/hzpx/qBxthAdY="
